#!/usr/bin/env python3
# encoding: utf8

import tkinter as tk
from tkinter import messagebox

w = tk.Tk()
w.withdraw()
w.after(5000, w.destroy) # Destroy the widget after 3 seconds
w.option_add('*Dialog.msg.font', 'Helvetica 12')
if messagebox.showinfo('EXEMPLARY SUSPENSION', 'EXEMPLARY SUSPENSION IS TRIGGERED,\n This window is triggered as an exemplary suspension action. The DA launched it based on <data> field in <susp> request from the TaskHarmoniserAgent!'):
    w.destroy()
