#!/usr/bin/env python2

from task_machine.StateMachine import * #StateMachine
from multitasker.srv import LaunchConditions,StartTask
from multitasker.msg  import *
from multitasker.srv  import *
from rospy_message_converter import json_message_converter
import json

import rospy
import time 
import datetime
import sys

# ------------------------------------------------------------------
from tf.transformations import euler_from_quaternion, quaternion_from_euler
import tf
import math
import geometry_msgs.msg
import actionlib
# ------------------------------------------------------------------
from tiago_utils import * # global constants
from tiago_utils import move_base_set_goal
from tiago_utils import move_base_cancel_goals
from tiago_utils import wait_for_tiago_init
from tiago_utils import action_status_callback
# ------------------------------------------------------------------

from nav_msgs.msg  import *
from nav_msgs.srv  import *
from visualization_msgs.msg import Marker
# --------------------------------
global listener
global human_id
global human_posture
global return_msg
global fsm_DA
human_posture = "stand"
return_msg = []
startFlag = False
my_priority = 0
is_interrupting = False

my_priority = 0 
my_completion_time = -1
is_interrupting = False

dock_pose = [3.70, 1.90, 0.0, 0.0, 0.0, 0.0] # next to entrance | y ~ PI - back to door 

# 'standing' script poses
# ===================
# ======= V1 ========
# ===================
'''
header: 
  seq: 0
  stamp: 
    secs: 105
    nsecs: 373000000
  frame_id: "map"
pose: 
  position: 
    x: 0.449645936489
    y: 0.0792762041092
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.97049860128
    w: -0.241106750038

human_pose = [0.45, 0.08, 0.0, 0.0, 0.0, -152.5]
'''
# ===================
# ======= V2 ========
# ===================
'''
header: 
  seq: 0
  stamp: 
    secs: 22
    nsecs: 330000000
  frame_id: "map"
pose: 
  position: 
    x: -0.1344743222
    y: -0.201279640198
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.999291688955
    w: -0.0376313750156
'''
#human_pose = [-0.13, 0.20, 0.00, 0.0, 0.0, 35.68]
# ===================

'''
  position: 
    x: 3.18645572662
    y: 5.37823104858
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.58703750871
    w: 0.80955973428
'''
#human_dest = [3.18, 5.37, 0.0, 0.0, 0.0, 71.89]

# human_dest = [2.92, 5.24, 0.0, 0.0, 0.0, 120.0]

# ===================

# ------------------------------------------------------------------

# Ver2
human_poses = []
human_dests = []
human_last_poses = []

# * * * * * * * * * * * * * * ACTOR1 * * * * * * * * * * * * * * * *

# start
'''
header: 
  seq: 8
  stamp: 
    secs: 243
    nsecs: 853000000
  frame_id: "map"
pose: 
  position: 
    x: -0.48579788208
    y: 0.14269067347
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.953078234364
    w: -0.302724097457
'''

#human_pose = [-0.4857, +0.0000, +0.0000, +0.0000, +0.0000, -144.7597]
#human_poses.append(human_pose)

'''
header: 
  seq: 1
  stamp: 
    secs: 374
    nsecs: 800000000
  frame_id: "map"
pose: 
  position: 
    x: -0.320914298296
    y: -0.100545883179
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.986417840476
    w: -0.164255423015
'''
#human_pose = [-0.3209, -0.1005, +0.0000, +0.0000, +0.0000, -161.0926]

human_pose = [2, 9, +0.0000, +0.0000, +0.0000, -161.0926]
human_poses.append(human_pose)
human_poses.append(human_pose)
human_poses.append(human_pose)


# dest 
'''
header: 
  seq: 9
  stamp: 
    secs: 292
    nsecs: 174000000
  frame_id: "map"
pose: 
  position: 
    x: 3.12596273422
    y: 5.67313241959
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.999757517577
    w: 0.0220205823641
'''
#human_dest = [+3.1259, +5.6731, +0.0000, 0.0000, 0.0000, +177.4764]
#human_dests.append(human_dest)

'''
header: 
  seq: 2
  stamp: 
    secs: 589
    nsecs: 850000000
  frame_id: "map"
pose: 
  position: 
    x: 3.41345524788
    y: 5.586145401
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.985469480681
    w: 0.169852590933
'''

human_dest = [+3.4134, +5.5861, +0.0000, 0.0000, 0.0000, +160.4415]
human_dests.append(human_dest)

# * * * * * * * * * * * * * * ACTOR2 * * * * * * * * * * * * * * * *
# start

'''
header: 
  seq: 12
  stamp: 
    secs: 395
    nsecs: 123000000
  frame_id: "map"
pose: 
  position: 
    x: 3.31662845612
    y: 1.70269775391
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.805676184728
    w: 0.592356214927

'''
#human_pose = [+3.3166, +1.7026, +0.0000, +0.0000, +0.0000, -107.3513]
#human_poses.append(human_pose)

'''
header: 
  seq: 3
  stamp: 
    secs: 677
    nsecs: 972000000
  frame_id: "map"
pose: 
  position: 
    x: 3.22058129311
    y: 1.03116691113
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.776372649676
    w: 0.63027415371

'''

#human_pose = [+3.2205, +1.0311, +0.0000, +0.0000, +0.0000, -101.8592]
human_pose = [3.97165822983, 4.85366201401, +0.0000, +0.0000, +0.0000, -101.8592]
human_poses.append(human_pose)

# dest

'''
header: 
  seq: 11
  stamp: 
    secs: 375
    nsecs: 113000000
  frame_id: "map"
pose: 
  position: 
    x: -0.552233695984
    y: -0.276034355164
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.0662988753729
    w: 0.997799809142
'''
#human_dest = [-0.5522, -0.2760, +0.0000, 0.0000, 0.0000, -7.6019]
#human_dests.append(human_dest)

'''
header: 
  seq: 4
  stamp: 
    secs: 734
    nsecs: 804000000
  frame_id: "map"
pose: 
  position: 
    x: -0.474497079849
    y: -0.41937148571
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.00422636600859
    w: 0.999991068875
'''

human_dest = [-0.4744, -0.4193, +0.0000, 0.0000, 0.0000, +0.4842]
human_dests.append(human_dest)

# ------------------------------------------------------------------

human_last_poses = human_poses # in fact - robot's last poses while guiding each human

# ------------------------------------------------------------------

human_name = ""
room_number = ""
global factor_walk
factor_walk = [0,0]
global factor_stand
factor_stand = [0,0]
global factor_sit
factor_sit = [0,0]
# walk factor for human 0
factor_walk[0] = 1
# walk factor for human 1
factor_walk[1] = 2
# sit factor for human 0
factor_sit[0] = 0.1
# sit factor for human 1
factor_sit[1] = 0.1
# stand factor for human 0
factor_stand[0] = 0.1
# stand factor for human 1
factor_stand[1] = 0.2


# ======================================================================================
def publish_human_pose():
    global marker_pub
    global marker
    marker_pub.publish( marker );

def add_marker(pose):
    global marker_pub
    global marker
    global human_id
    marker_pub = rospy.Publisher("ellipse", Marker)
    marker = Marker();
    marker.header.frame_id = "map";
    marker.header.stamp = rospy.Time.now();
    marker.ns = "human";
    marker.id = human_id;
    marker.type = Marker.CYLINDER
    marker.action = Marker.ADD
    marker.pose.position.x = pose[0]
    marker.pose.position.y = pose[1]
    marker.pose.position.z = 0.5
    marker.pose.orientation.x = 0.0
    marker.pose.orientation.y = 0.0
    marker.pose.orientation.z = 0.0
    marker.pose.orientation.w = 1.0
    marker.scale.x = 0.3
    marker.scale.y = 0.3
    marker.scale.z = 1
    marker.color.a = 1.0 
    marker.color.r = 0.0 
    marker.color.g = 1.0 
    marker.color.b = 3.0 - human_id
    marker_pub.publish( marker )

def remove_marker():
    global marker_pub
    global marker
    global human_id
    marker.header.frame_id = "map";
    marker.header.stamp = rospy.Time.now();
    marker.ns = "human";
    marker.id = human_id;
    marker.type = Marker.CYLINDER
    marker.action = Marker.DELETE
    marker_pub.publish( marker );

def blocking_call(queue):

    try:
        args = queue.get()
        i =0
        print(str(datetime.datetime.now().time())+"\n"+ args+"\n")
        x = args[0]
        y = args[1]
        z = args[2]
        print(str(datetime.datetime.now().time())+"\n"+ "Z: ", z+"\n")
        while i < 100:
            x+=1
            y+=1
            z+=1
            time.sleep(1)
            i+=1
        print(str(datetime.datetime.now().time())+"\n"+ "computed: "+ str([x, y, z])+"\n")
        queue.put([x,y,z])
    finally:
        print(str(datetime.datetime.now().time())+"\n"+ "EXCEPTTTTTTTTTTTTTTTTTTTTT"+"\n")
    return

# ======================================================================================

def start(cargo_in, event_in, event_out):

    print("\n"+ "----------"+"\n")
    print( "START"+"\n")
    print( "----------"+"\n")
    print("\t cargo: "+ str( cargo_in)+"\n")
    print("\t STATE_EVENT: "+ str( event_in.isSet())+"\n")
    print( ""+"\n")

    global human_id

    # if event_in.isSet():
    #     event_out.set()
    #     print( ""+"\n")
    #     print( "set HOLD"+"\n")
    #     print( ""+"\n")
    #     return ("first_hold", "data required to hold")

    return ("move_to_human", [human_name, None])

# ======================================================================================

def move_to_human(cargo_in, event_in, event_out):
    global last_exec_state_name
    global human_ok
    last_exec_state_name = "move_to_human"

    print(str(datetime.datetime.now().time())+"\n"+ "----------"+"\n")
    print( "move_to_human"+"\n")
    print("----------"+"\n")
    print( "\t args [<human_name>, <init_human_pose>]: "+ str( cargo_in)+"\n")
    print( "\t Get pose of the human "+"\n")
    
    i = 0

    global human_poses
    global human_id
    global return_msg

    # first try
    print ( "\t     1st \t human_id: " + str(human_id) + "\t pose hard-coded: " + str(human_poses[human_id]) )
    client = move_base_set_goal( human_poses[human_id] )


    while ( client.get_state() != ACTION_STATUS_SUCCEEDED):
        
        print( "\t Moving to the human: "+ str( cargo_in[0])+"\n")
        print( "\t Checking if the destination is reached"+"\n")
        #print( "\t       o  move base STATE: " + str(client.get_state()) +"\n")

        # run_blocking(blocking_call, cargo_in, event)
        
        if (event_in.isSet() or human_ok==True):
            event_out.set()
            print( ""+"\n")
            print( "set HOLD"+"\n")
            print( ""+"\n")
            return ("suspending", "move_to_human")
        
        rospy.sleep(1)
        i+=1
    return ("observe_report", None)

# ======================================================================================

def hold_moving(cargo_in):

    print(str(datetime.datetime.now().time())+"\n"+ "----------"+"\n")
    print("hold_moving"+"\n")
    print( "----------"+"\n")
    print("\t args: "+ str( cargo_in)+"\n")

    move_base_cancel_goals()

    global human_name
    global room_number
    global human_ok

    # run_blocking(blocking_call, cargo_in, event)
    #return ("move_to_human", [human_name, human_last_poses[human_id]])
    if human_ok:
        return ("final", None)
    return ("move_to_human", return_msg )

# ======================================================================================

def observe_report(cargo_in, event_in, event_out):
    global last_exec_state_name
    last_exec_state_name = "observe_report"

    print(str(datetime.datetime.now().time())+"\n"+ "----------"+"\n")
    print( "observe_report"+"\n")
    print("----------"+"\n")
    i=0
    print( "\t RECORD_VIDEO\n")
    print( "\t SAY_METHOD("+ "Hello, can you hear me? Are yoou OK?"+")\n")

    while i < 5:

        print( "\t Checking if the speech is over"+"\n")
        # run_blocking(blocking_call, cargo_in, event)
        i=i+1
        rospy.sleep(1)
    print( "\t SENDING REPORT\n")
    return ("final", None)

# ======================================================================================

def suspending(cargo_in):

    print(str(datetime.datetime.now().time())+"\n"+ "----------"+"\n")
    print( "suspending"+"\n")
    print("----------"+"\n")
    print( "\t args: "+ str( cargo_in)+"\n")
    i = 0
    # -------
    # getSuspend
    # -------
    global return_msg
    global last_exec_state_name
    global human_posture
    last_exec_state_name = cargo_in

    print(str(datetime.datetime.now().time())+"\n"+ "----------"+"\n")
    print("hold_moving"+"\n")
    print( "----------"+"\n")
    print("\t args: "+ str( cargo_in)+"\n")

    move_base_cancel_goals()


    # run_blocking(blocking_call, cargo_in, event)
    #return ("move_to_human", [human_name, human_last_poses[human_id]])

    return_msg = []
    return_msg.append(human_name)
    return_msg.append(human_last_poses[human_id])

    return ("resume_state", None)



# ======================================================================================

def resume_state(cargo_in, event_in, event_out):

    print(str(datetime.datetime.now().time())+"\n"+ "----------"+"\n")
    print( "resume_state"+"\n")
    print("----------"+"\n")
    print( "\t args: "+ str( cargo_in)+"\n")
    print("----------"+"\n")
    print( "\t interupted state : "+ str( cargo_in[0])+"\n")
    i = 0
    global return_msg
    return ("move_to_human", return_msg )

# ======================================================================================

def final(cargo_in, event_in, event_out):
    move_base_cancel_goals()
    return
def getSP():
    publish_human_pose()
    sp = ScheduleParams()
    print "CALC COST"
    global factor_walk
    global factor_stand
    global factor_sit
    global human_poses
    global fsm_DA
    global human_ok
    path_client = rospy.ServiceProxy('/move_base/GlobalPlanner/make_plan', GetPlan)
    req_path = GetPlanRequest()
    ros_time = rospy.Time()
    trans = []
    rate = rospy.Rate(5.0)
    while rclpy.ok():
        try:
            listener.waitForTransform('/map', '/base_link', ros_time, rospy.Duration(8.0))
            (trans,rot) = listener.lookupTransform('/map', '/base_link', ros_time)
            if len(trans) != 0:
                break
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            rate.sleep()
            continue

    path_distance = 0
    req_path.start.header.frame_id = "map"
    req_path.start.pose.position.x = trans[0]
    req_path.start.pose.position.y = trans[1]
    req_path.start.pose.position.z = trans[2]
    req_path.start.pose.orientation.x = rot[0]
    req_path.start.pose.orientation.y = rot[1]
    req_path.start.pose.orientation.z = rot[2]
    req_path.start.pose.orientation.w = rot[3]
    req_path.goal.header.frame_id = "map"
    req_path.goal.pose.position.x = human_poses[human_id][0]
    req_path.goal.pose.position.y = human_poses[human_id][1]
    req_path.goal.pose.position.z = human_poses[human_id][2]
    req_path.goal.pose.orientation.x = 0
    req_path.goal.pose.orientation.y = 0
    req_path.goal.pose.orientation.z = 0
    req_path.goal.pose.orientation.w = 0
    resp = path_client(req_path)
    # print "PATH LENGTH: ",len(resp.plan.poses)
    path_distance_approach = 0
    if len(resp.plan.poses) > 2:
        for i in range(len(resp.plan.poses)-1):
            # print "POSE: ",resp.plan.poses[i]
            path_distance_approach += math.sqrt(math.pow((resp.plan.poses[i+1].pose.position.x - resp.plan.poses[i].pose.position.x),2) + pow((resp.plan.poses[i+1].pose.position.y - resp.plan.poses[i].pose.position.y), 2))
    print "COST: ", path_distance_approach
    sp.cost = path_distance_approach
    sp.cost_per_sec = 1
    sp.completion_time = path_distance_approach
    sp.final_resource_state.robot_position = req_path.goal.pose.position
    human_ok = rospy.get_param("~human_ok", False)
    if human_ok:
        fsm_DA.terminate()
    return sp

def ptf_update_task(state_machine,TH_data):
    global last_exec_state_name
    print "UPDATEING TASK - 3"
    print "UPDATE_TASK UPDATE_TASK UPDATE_TASK: ", type(state_machine)
    state_machine.add_state("resume_state", resume_state,None)
    return ("resume_state", last_exec_state_name)

def ptf_update_sp():
    return getSP()

def ptf_suspend_condition(suspend_request):
    global human_posture
    global last_exec_state_name
    global human_id
    global human_poses
    suspend_response = SuspendConditionsResponse()
    ##
    # plan to get cost from final state given by a candidate for interrupting task to the state required by this DA 
    ##
    path_client = rospy.ServiceProxy('/move_base/GlobalPlanner/make_plan', GetPlan)
    req_path = GetPlanRequest()
    ros_time = rospy.Time()
    trans = []
    rate = rospy.Rate(5.0)
    while rclpy.ok():
        try:
            listener.waitForTransform('/map', '/base_link', ros_time, rospy.Duration(8.0))
            (trans,rot) = listener.lookupTransform('/map', '/base_link', ros_time)
            if len(trans) != 0:
                break
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            rate.sleep()
            continue

    path_distance = 0
    req_path.start.header.frame_id = "map"
    req_path.start.pose.position = suspend_request.final_resource_state.robot_position
    req_path.start.pose.orientation.x = 0
    req_path.start.pose.orientation.y = 0
    req_path.start.pose.orientation.z = 0
    req_path.start.pose.orientation.w = 0
    req_path.goal.header.frame_id = "map"
    req_path.goal.pose.position.x = human_poses[human_id][0]
    req_path.goal.pose.position.y = human_poses[human_id][1]
    req_path.goal.pose.position.z = human_poses[human_id][2]
    req_path.goal.pose.orientation.x = 0
    req_path.goal.pose.orientation.y = 0
    req_path.goal.pose.orientation.z = 0
    req_path.goal.pose.orientation.w = 0
    resp = path_client(req_path)
    # print "PATH LENGTH: ",len(resp.plan.poses)
    path_distance_approach = 0
    if len(resp.plan.poses) > 2:
        for i in range(len(resp.plan.poses)-1):
            # print "POSE: ",resp.plan.poses[i]
            path_distance_approach += math.sqrt(math.pow((resp.plan.poses[i+1].pose.position.x - resp.plan.poses[i].pose.position.x),2) + pow((resp.plan.poses[i+1].pose.position.y - resp.plan.poses[i].pose.position.y), 2))
    
    suspend_response.cost_per_sec = 1
    suspend_response.cost_to_resume = path_distance_approach * suspend_response.cost_per_sec
    return suspend_response 

def ptf_cost_condition(cost_request):
    global human_posture
    global last_exec_state_name
    global human_id
    global human_poses
    cost_response = CostConditionsResponse()
    ##
    # plan to get cost from final state given in request to the state required by this DA 
    ##
    path_client = rospy.ServiceProxy('/move_base/GlobalPlanner/make_plan', GetPlan)
    req_path = GetPlanRequest()
    ros_time = rospy.Time()
    trans = []
    rate = rospy.Rate(5.0)
    while rclpy.ok():
        try:
            listener.waitForTransform('/map', '/base_link', ros_time, rospy.Duration(8.0))
            (trans,rot) = listener.lookupTransform('/map', '/base_link', ros_time)
            if len(trans) != 0:
                break
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            rate.sleep()
            continue

    path_distance = 0
    req_path.start.header.frame_id = "map"
    req_path.start.pose.position = cost_request.final_resource_state.robot_position
    req_path.start.pose.orientation.x = 0
    req_path.start.pose.orientation.y = 0
    req_path.start.pose.orientation.z = 0
    req_path.start.pose.orientation.w = 0
    req_path.goal.header.frame_id = "map"
    req_path.goal.pose.position.x = human_poses[human_id][0]
    req_path.goal.pose.position.y = human_poses[human_id][1]
    req_path.goal.pose.position.z = human_poses[human_id][2]
    req_path.goal.pose.orientation.x = 0
    req_path.goal.pose.orientation.y = 0
    req_path.goal.pose.orientation.z = 0
    req_path.goal.pose.orientation.w = 0
    resp = path_client(req_path)
    # print "PATH LENGTH: ",len(resp.plan.poses)
    path_distance_approach = 0
    if len(resp.plan.poses) > 2:
        for i in range(len(resp.plan.poses)-1):
            # print "POSE: ",resp.plan.poses[i]
            path_distance_approach += math.sqrt(math.pow((resp.plan.poses[i+1].pose.position.x - resp.plan.poses[i].pose.position.x),2) + pow((resp.plan.poses[i+1].pose.position.y - resp.plan.poses[i].pose.position.y), 2))
    cost_per_sec = 1
    cost_response.cost_to_complete = path_distance_approach * cost_per_sec
    return cost_response 
# ======================================================================================

if __name__== "__main__":

    try:
        global debugging
        debugging = False 
        global startFlag
        global my_priority
        global my_deadline
        global human_poses
        global last_exec_state_name
        global marker
        global fsm_DA
        global human_ok
        human_ok = False
        marker = Marker()
        last_exec_state_name = "None"
        # global human_last_poses
        global human_id
        version = sys.argv[1]
        da_name = sys.argv[2]
        sp = ScheduleParams()
        da_ID = int(sys.argv[3])
        stri = sys.argv[4]
        rospy.init_node(da_name, anonymous=False)
        print "DA: ",stri
        # sp = json_message_converter.convert_json_to_ros_message('multitasker/ScheduleParams', stri)
        # print "\n\n\nDA.cost: ", sp.cost
        # my_cost = sp.cost
        # my_completion_time = sp.completion_time
        # print ("my_completion_time = ", sp.completion_time) 
        print ("version = ", version) 
        if version == "fell-0":

            human_name = "John"
            room_number = "10"
            human_id = 2

        elif version == "fell-1":

            human_name = "Mark"
            room_number = "15"
            human_id = 3

        else:

            print('\t WRONG da_name...')
            rospy.sleep(3)
        f_name_1 = "./blockin_log"+version
        f_name_2 = "./state_m_log"+version
        f1=open(f_name_1, 'w+')
        f2=open(f_name_2, 'w+')

        debugging = True 

        rospy.init_node(da_name, anonymous=False)
            
        listener = tf.TransformListener()
        rospy.sleep(2)
        # wait_for_tiago_init()

        add_marker(human_poses[human_id])
        fsm_DA = StateMachine(f2, is_interrupting, da_ID, ptf_update_task, ptf_update_sp, ptf_suspend_condition, ptf_cost_condition)
        fsm_DA.add_state("Start", start, None)
        fsm_DA.add_state("suspending", suspending, None)
        fsm_DA.add_state("move_to_human", move_to_human, None)
        fsm_DA.add_state("hold_moving", hold_moving, None)
        fsm_DA.add_state("observe_report", observe_report, None)
        #fsm_DA.add_state("go_to_dock", go_to_dock, None) # for testing
        fsm_DA.add_state("final", final, end_state=True)
        fsm_DA.set_start("Start")
        fsm_DA.run("Python is great")
        #fsm_DA.run("Python is difficult")
        #m.run("Perl is ugly")

    finally:
        print "ERROR"
        global human_poses
        global human_id
        if marker.header.frame_id != "":
            remove_marker()
        global debugging
        if debugging: 
            f1.close()
            f2.close()

# ======================================================================================        

